Feature design / rfc: Formation flying
EndlessSkyCommunity/endless-sky pull request #52
Opened 2019-11-05 18:07 UTC by petervdmeer

I combined the different formation flying features descriptions into a single rfc/feature design Markdown document to allow for easier and more efficient review of this feature.

2020-04-13 05:48 UTC, kikotheexile commented
This is honestly brilliant in concept and feels like a feature i would want out of most games i play, but i feel like its functionality is extremely limited in ES. 

Formations and postures like this assume same top speed, acceleration, and maneuverability for such quick in-and-out jumps and engagements we see in ES.  So although its rad as fuck, its not getting the utility it needs from the game environment itself. 

An amazing idea, a massive fish in a tiny pond, but systems need expanded to really get the full potential of this. 

I still love it and want to see it finished tho.

2020-04-13 09:18 UTC, MCOfficer approved these changes
Not commenting on the implementation/data format, just the feature.

I largely agree with kiko, for largely the same reasons. However, a quick glance at the "desired functionality" section tells you exactly why this is a great feature. It's a much needed first step, even though it won't bring a lot of immediate benefit.

2020-04-13 14:22 UTC, Zitchas approved these changes
I haven't worked out all the math for the patterning, but this looks like all the sort of information I'd need to play with building my own fleets. 

This is definitely something that I think will add a lot of detail and interest to the game.

2020-04-19 00:34 UTC, tehhowch requested changes
Thanks for writing up the RFC! The biggest request here is to basically revise it all, to use a more RFC-like language. The idea behind these is that, upon adopting one, we have a definite guideline / specification. It is good to acknowledge the departure from current behavior, but divulging implementation details isn't appropriate unless we are debating between implementations.

I didn't get to the latter part of the RFC, and will hold off on reviewing it until after an update.

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +## Highly desired but currently not implemented functionaly
We should be prescriptive with RFC language and content - the goal is to outline how the thing will work. A detailed accounting of things that don't work yet doesn't quite belong in a description of how things will work.

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +The positions in a formation as implemented in [ES-#4471](https://github.com/endless-sky/endless-sky/pull/4471) exclusively depend on the position and movement direction of the lead ship.
I would expect this section to describe the goal for turning. If there are multiple desired-yet-exclusive behaviors, this section should identify each of them and identify the associated data keyword used to select the behavior.

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +Actual formation positions are determined by the order in which ships are in the ships-list and only applies to ships in the system. If formation-flying ships from outside the system join, then they
This sounds like a current implementation detail. Is the desired goal to have ships behave in this way?

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +		rotational <nr>
Please use the [same syntax](https://github.com/endless-sky/endless-sky/wiki/DataFormat#grammar-specifications) as the wiki for identifying data types

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- `line <x> <y> <slots> <direction>`: Begins a line at position x,y for a line with `<slots>` positions for ships. The very first ship in the line is at exactly x,y, the line stretches into the direc
You should include examples in these sections. For example, what are the prescribed values of a direction? Up? Forward? North?

Also, does it make sense to perhaps support a syntax like
```
line [<shipCount#>]
  start <x1#> <y1#> # defaults to (0, 0)
  end <x2#> <y2#>
```

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- `arc <refX> <refY> <radius> <angle> <segment>`: Specify partial or full circle segment. `<refX>` and `<refY>` specify the anchor/reference point for the arc.
Use `center` instead of `ref` - I think it is more commonly associated with your intended use in mathematics / algebra / geometry.

Also, does it make sense to use named parameters e.g.
```
arc 0 0 100 -45 45
``` 
vs
```
arc 100
  center 0 0 # default 0 0
  degrees -45 45 # default 0 360
```

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +   - `<angle>` specifies the direction to the start point of the arc angle (0 to 360)
What sign convention does this use? I think for ease of use we should adopt standard mathematical convention - the game implementation can handle the conversion to graphics convention.

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +   - `<segment>` (-360 to 360) specifies how much of a circle is used; 0 is single formation position, 90 is a quarter circle, 360 is a full circle, an positive segment is clockwise, a negative segme
I think degrees is a better label

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +   - `"nofirst"`: Don't fill the first position (starting position) of the arc. Usefull if another line or arc fills that position.
Maybe these should be child nodes, "skip", taking a number or the keywords "start" and "end". This child node could also work for lines then, where the specific slot number to skip can be easily computed.

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- (arc) `spacing <nr>`: Specifies the minimum amount of spacing between ships on the arc. Ship positions are evenly spaced among the arc, with at least the minimum as given here.
Should spacing should be interpreted the same for both geometry elements? It seems like there is differing behavior for arcs and lines, due to the different styles of start and end specification.

2020-04-19 00:34 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- (arc) `repeat <deltaRadius>`: Specifies the repeat vector among which this arc is repeated.
A vector requires two parameters.

I'm also of the opinion that we should try to make a repeat node be interpreted similarly for arcs and lines, i.e. have the same child nodes

2020-04-19 03:25 UTC, toilethinges approved these changes
This looks really cool! Without looking at the code, I definitely think this is a great feature and one that I think would be really interesting to have in the game.

2020-04-19 11:43 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +## Highly desired but currently not implemented functionaly
We also want the things that don't work yet to be working in the future. But I just changed the text to a description to "how things should be working" without much reference to what is working today.

2020-04-19 11:45 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +The positions in a formation as implemented in [ES-#4471](https://github.com/endless-sky/endless-sky/pull/4471) exclusively depend on the position and movement direction of the lead ship.
There are multiple desired behaviours, but they are not mutually exclusive. The keywords for symmetry are described, I don't see a need for other keywords after the update I just did.

2020-04-19 12:09 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +Actual formation positions are determined by the order in which ships are in the ships-list and only applies to ships in the system. If formation-flying ships from outside the system join, then they
If we have different types of ships in a single formation (for example Heavy Freighters and Interceptors), then this would allow the player some controls to ensure that the Heavy Freighters are more to the inside of the formation while the Interceptors would go more to the outside of the formation.

The ring-settings however also allow for a similar type of control, so we could also choose that we want "first come - first position" formations and handle what goes to the inside and what goes to the outside only through the ring-settings.

Implementation wise it doesn't make much difference. Both are quite straight-forward to implement.

2020-04-19 12:11 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +		rotational <nr>
Should be better now after my last update.

2020-04-19 12:13 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `line <x> <y> <slots> <direction>`: Begins a line at position x,y for a line with `<slots>` positions for ships. The very first ship in the line is at exactly x,y, the line stretches into the direc
Yes, I was doubting about supporting multiple definition formations, but this makes a lot of sense.
I might also include polar coordinates as possible method to specify coordinates.

2020-04-19 12:14 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `arc <refX> <refY> <radius> <angle> <segment>`: Specify partial or full circle segment. `<refX>` and `<refY>` specify the anchor/reference point for the arc.
Yes, center is more appropriate. And named parameters looks a lot more readable indeed.

2020-04-19 12:16 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - `<angle>` specifies the direction to the start point of the arc angle (0 to 360)
I will add some specification here on the units and conventions used for those numbers.

2020-04-19 13:07 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- (arc) `spacing <nr>`: Specifies the minimum amount of spacing between ships on the arc. Ship positions are evenly spaced among the arc, with at least the minimum as given here.
Both those differences comes from the difference in the "repeat" behaviour;
- for lines you can calculate upfront how many slots there are in each repeated line (and specify all line/slots information upfront).
- I don't know a simple specification to do the same for the arc sections; as sections grow there will be more and more slots to add more ships, but not in a linear sense as with lines.

The difference in start and end specification is also due to the "repeat" behaviour difference. For lines I always know where it starts and ends and if I want to skip a start or end slot, then I can just make the line 1 slot shorter (and calculate the new start position if it was the start I was changing).
For arcs I cannot determine the exact ship slot positions of the follow-up/repeated lines with a simple definition. And to be able to connect 2 arc sections I need to be able to perform skip on one of them (to avoid having 2 ships on the same formation position).
Alternatives are to accept gaps between the sections, accept overlapping positions, automatically detect overlapping positions or to always leave out the start and the end positions for arcs.
Always leaving out the start and end positions might be better (to keep the specification simpler and the amount of exceptions smaller), I'll update the specification for that.

2020-04-19 13:09 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- (arc) `repeat <deltaRadius>`: Specifies the repeat vector among which this arc is repeated.
Each repeated arc uses the same center, the same direction for start, the same direction for end but a different radius. Maybe I should change the word vector here.

2020-04-19 13:12 UTC, petervdmeer commented
Document is largely rewritten (as requested by @tehhowch); this RFC now describes how formations should work without any reference to what is currently working and what not.

I still have some review-comments to process.

2020-04-19 13:52 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - `<segment>` (-360 to 360) specifies how much of a circle is used; 0 is single formation position, 90 is a quarter circle, 360 is a full circle, an positive segment is clockwise, a negative segme
Degrees is an unit of measurement, not a measured property itself. I would prefer a keyword that describes the measured property, not the unit in which it is measured.

2020-04-19 14:20 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +   - `<segment>` (-360 to 360) specifies how much of a circle is used; 0 is single formation position, 90 is a quarter circle, 360 is a full circle, an positive segment is clockwise, a negative segme
I'm not sure what the more appropriate usage guideline label for the angular measure of an arclength would be. "segment" just doesn't seem to fit when the intent is to convey something like "this is an arc centered on (X, Y) with a radius of 100 that starts at an angle of 30° and spans 90°"
Having written that, I think "`<span#>`" makes more sense than "`<segment#>`".

I also am not sure if it makes sense to use the syntax here, where we define the starting angle and the angular span of the arc: specifying the starting and ending angles of the arc seems just as valid (and unfortunately has the same signature of "number number" if done on a single line).

2020-04-19 17:19 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - `<angle>` specifies the direction to the start point of the arc angle (0 to 360)
For ease of use I for now used the Endless Sky convention where possible.

2020-04-19 17:20 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - `<segment>` (-360 to 360) specifies how much of a circle is used; 0 is single formation position, 90 is a quarter circle, 360 is a full circle, an positive segment is clockwise, a negative segme
This information is now (embedded) in the start and the end keywords/tags.

2020-04-19 17:21 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - `"nofirst"`: Don't fill the first position (starting position) of the arc. Usefull if another line or arc fills that position.
Those keywords have been completely removed.

2020-04-19 17:21 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- (arc) `repeat <deltaRadius>`: Specifies the repeat vector among which this arc is repeated.
I made some changes to make the keywords more similar. The deltaRadius is now embedded in the start (and the end) tags.

2020-04-19 19:58 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +Actual formation positions are determined by the order in which ships are in the ships-list and only applies to ships in the system. If formation-flying ships from outside the system join, then they
I just added an example of the ring feature in https://github.com/endless-sky/endless-sky/pull/4471 to give an impression of how that part should work.

2020-04-19 20:53 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `arc <refX> <refY> <radius> <angle> <segment>`: Specify partial or full circle segment. `<refX>` and `<refY>` specify the anchor/reference point for the arc.
I changed to `anchor`, which I think is commonly used in other programs. If you prefer center then I can change it to center.

2020-04-21 16:58 UTC, tehhowch reviewed
I have more comments but not the time to formulate them, so here's some more feedback.

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- Coordinate signs (plus/minus) in formation definitions follow the default Endless Sky convention;
If it is helpful, you can upload a file (to `rfcs/imgs/<descriptive-name>`) and embed it in this document.

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- Coordinate axis lengths (both for carthesian as well as distances in polar coordinates) in formation definitions are measured in ship sizes, where 1 corresponds to the radius of the largest ship ac
A downside of this is that you cannot define a formation with a particular antimissile range unless you also limit which ships can participate in the formation. However, I think it would be possible to use a keyword when referring to the formation pattern that determines where the pattern gets the scale magnitude. For example, you might want one instance of a Delta formation to treat the unit length as 400 px, and a different instance to treat the unit length as the largest sprite height or width of participating ships.

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +	symmetry [transverse] [longitudinal]
It might be worth just using "x" or "y" instead of the more formal names.

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +      - The use of the ships-list order allows players some control over which ships appear where in the formations.
This doesn't seem to work with the previous statements re: symmetry. If the front can become the back, or the left the right, or if we have e.g. hexagonal rotational symmetry, doesn't that mean we can lose the ordering intentions?

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- `class <shipclass>`: Indicates for fleets/governments that the given formation should only be applied to the given class of ships. (TODO: attributes filter instead of class?)
I would suggest using a keyword that introduces a locationfilter definition, which would allow you to select applicable ships just like you would for an assisting or boarding mission

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- `ring <nr#>`: Area in the formation where the ship should appear (higher numbers is more outwards on most formations).
I thought the order in the formation was based on the ship list ordering?

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- `reference mission`: Form formation around mission (NPC) ships. Ships using this reference are evenly distributed around mission ships.
There are a lot of missions that could be active at once - does this take a mission name, e.g. so NPCs from an optional side quest know which other mission's ships they're supposed to protect?

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- `reference planets <nr1#> [<nr2#>]`: Form formation around the `<nr1>`th planet in the system. If two numbers are given, then form formations around all planets in the range `<nr1>-<nr2>`. If `<nr2
I don't think this syntax is particularly useful, and it's probably prone to issues when events modify systems. In general, you cannot assume that map.txt is the state of a player's map at any given time

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +- `reference wormholes <nr1#> [<nr2#>]`: Form formation around the `<nr1>`th wormhole in the system, similar to planets (with ranges). This allows for NPC pirates to form an ambush around a wormhole.
Wormholes are always named planets and the system + planet combination is unique identifier

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +This is used in savegames to store the formation used by the ship.
This seems extremely implementation dependent - I don't think we should prescribe in the RFC how formation information gets serialized on instantiated fleets.

I think the important thing to prescribe is the `fleet` and `npc` usage, as this is how a mission writer could use the feature.  
To me, a formation requires more than one ship, and so we should not explicitly allow setting the formation behavior at the ship level. (If the specific implementation makes that implicitly possible, that's fine, but it shouldn't be an advertised feature.)

2020-04-21 16:58 UTC, tehhowch commented on docs/rfcs/formation_flying.md
> +	line <direction#>
There isn't a description for the required parameter below

2020-04-21 18:54 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +      - The use of the ships-list order allows players some control over which ships appear where in the formations.
Good catch!

When I was thinking about the keywords for symmetry, then I was mostly thinking about the protective formations that have the flagship in the center. The current "center oriented" formations are ordered "inside to outside"; so if you have the ships ordered in a way that all your heavy transport ships are on the inside of the formation, then they will still be on the inside of the formation when the formation is rotated, flipped or mirrored.

Most formations that are "tailing" are ordered "front to back" and most formations that are "ahead" are ordered "inside to outside". Those can be flipped along the y-axis and still have the same type of ships at the front and center of the formation. I never considered to give them other symmetry settings.

I added some text to the RFC that symmetry is only for symmetry properties around the formation center.

2020-04-21 19:06 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `reference mission`: Form formation around mission (NPC) ships. Ships using this reference are evenly distributed around mission ships.
This setting was actually intended for players that fly around with active missions; form a formation around all the NPC ships that accompany the player.

But I decided to remove this keyword completely now that I thought a bit more about this; there can be many different missions active at any time:
- Some NPCs that follow the player can be hostile. Forming a formation around then is not a good idea.
- Some NPCs are fighters/fleets that join the player into battle. Forming a formation around friendly fighters and warships would also be odd.
- Some NPCs that follow the player have formations of their own. The interaction between the formations could become complex and unpredictable.

2020-04-21 19:07 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `reference planets <nr1#> [<nr2#>]`: Form formation around the `<nr1>`th planet in the system. If two numbers are given, then form formations around all planets in the range `<nr1>-<nr2>`. If `<nr2
Agreed, I will remove this one.

2020-04-21 19:10 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `reference wormholes <nr1#> [<nr2#>]`: Form formation around the `<nr1>`th wormhole in the system, similar to planets (with ranges). This allows for NPC pirates to form an ambush around a wormhole.
Changed to explicit names (with the system name being optional).

2020-04-21 19:22 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +	line <direction#>
Sorry, the keyword was no longer used here (replaced by `angle` on the start keyword).

2020-04-21 20:29 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +This is used in savegames to store the formation used by the ship.
I removed the ship keyword. It is indeed not relevant for mission writers, but what we write here will also be relevant for programmers that implement the feature.

2020-04-21 20:37 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `ring <nr#>`: Area in the formation where the ship should appear (higher numbers is more outwards on most formations).
There are 2 mechanisms described in this RFC to determine formation positions;
The ring mechanism overrides the ships-list-ordering. Ships with a higher ring are always (later/more outside/more back/more to the end) of the formation and rings can also ensure that space in (the beginning/more inside/more to to front/more to the begin) of the formation is left empty.

Here is the example from #4471 where the center of a delta formation is left empty by using a ring setting for the ships in the delta-formation: ![formations_ring_example](https://user-images.githubusercontent.com/35403542/79698287-50bdca80-8288-11ea-86ce-aaf65ecef3a7.png)

2020-04-21 20:46 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- Coordinate axis lengths (both for carthesian as well as distances in polar coordinates) in formation definitions are measured in ship sizes, where 1 corresponds to the radius of the largest ship ac
That is true. If you want to define formations using very exact positions in px, then you also need to be able to set an exact unit length (or only use one type of ship in the formation).

If we add the keyword for scaling to the formation definition, then we would get 'auto-scaling' formations and 'exact position' formations. Those formations behave quite differently, so I think that that is nicer than adding it to the sections where we attach a formation to a fleet or npc. Do you agree?

2020-04-21 21:05 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +	symmetry [transverse] [longitudinal]
Yes, that might just fit better. Changed accordingly (and used the formal names in the description).

2020-04-21 21:16 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `class <shipclass>`: Indicates for fleets/governments that the given formation should only be applied to the given class of ships. (TODO: attributes filter instead of class?)
Yes, a location filter is the appropriate filter, it can select on things like attributes, categories and on outfits.

2020-04-21 21:41 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `reference wormholes <nr1#> [<nr2#>]`: Form formation around the `<nr1>`th wormhole in the system, similar to planets (with ranges). This allows for NPC pirates to form an ambush around a wormhole.
Also combined planet and wormhole into single object definition.

2020-04-21 21:51 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- Coordinate signs (plus/minus) in formation definitions follow the default Endless Sky convention;
Yes, but this could also be a "less is more" situation. If I look at the `"engine"` keyword in https://github.com/endless-sky/endless-sky/wiki/CreatingShips, then it just says;

"engine": the (x, y) coordinates, relative to the center of the sprite, where engine flares should appear. Positive y is up; negative y is down"

This describes with a lot less words how the ships coordinate work (x is not specified at all, probably because it works as everybody expects).

2020-04-21 21:56 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- Coordinate signs (plus/minus) in formation definitions follow the default Endless Sky convention;
I tried to simplify the text a bit based on this example.

2020-04-22 21:10 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `class <shipclass>`: Indicates for fleets/governments that the given formation should only be applied to the given class of ships. (TODO: attributes filter instead of class?)
Changed to locationfilter yesterday.

2020-06-04 22:40 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- Coordinate axis lengths (both for carthesian as well as distances in polar coordinates) in formation definitions are measured in ship sizes, where 1 corresponds to the radius of the largest ship ac
I added px-based formations as default and also allow size-based formations as option.

2020-06-04 22:42 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- (arc) `spacing <nr>`: Specifies the minimum amount of spacing between ships on the arc. Ship positions are evenly spaced among the arc, with at least the minimum as given here.
I updated the specification to be more explicit about which keyword applies to lines and which to arcs and how they apply differently.

2020-06-04 22:43 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `line <x> <y> <slots> <direction>`: Begins a line at position x,y for a line with `<slots>` positions for ships. The very first ship in the line is at exactly x,y, the line stretches into the direc
Defaults and directions should now be in the specification. Polar coordinates as well.

2020-06-04 22:43 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +Actual formation positions are determined by the order in which ships are in the ships-list and only applies to ships in the system. If formation-flying ships from outside the system join, then they
Ring settings are now explicitly mentioned in this section as well.

2020-06-13 00:45 UTC, thomasballinger reviewed
This seems well thought out. The only thing I think I want is the ability to fill lines from the middle instead of from start to end.

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +- (x,y) coordinates are relative to the center of the formation(pattern), with coordinate 0,0 being the center, with positive x being towards the right side of the formation and positive y being towa
Is the center of the formation always a ship? (I'm pretty sure yes, but was confused about this when I first read it)

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +- `symmetry [x] [y]`: Indicates if a formation should be considered symmetric. Symmetric formations allow for nicer and more desired behaviour on turns.
Another possible name for this is `allow-flip x` or `flippable x`; might reflect better what this does.

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +   - `rotational <nr#>`: Indicates rotational symmetry (nr is in range 0 to 360). Rotational symetric formations don't need to turn fully to become aligned with the leadship/reference again.
- I think I might want to use small n here, like 1. Will that be ok implementation-wise?
- Would using rotational symmetry order (3 for a triangle, 5 for a pentagon) might clearer here? I'm not sure it would, just an idea.

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +- `line`: Begins a line.
I sort of want a line that grows from the middle out. Not sure if it makes sense for this to be a property in here.

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +      - The default spacing is 2; so twice the radius of the largest ship in the formation.
Should this say "The default spacing is radius 2?"

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +         - If a line has an end-coordinate, slots and no spacing, then spacing is automatically calculated (instead of the default being used).
Both an implementation and spec note: it maybe useful to validate formations are not over-constrained at load time or spit out warnings, whatever the pattern is for invalid data. These notes about what will happen in over-constrained situations are great, but if there's no possible need for some combinations of properties it might be nice to make them warn or be invalid.

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +      - Or the amount of slots to increase/decrease on each growth step when given in a line repeat section.
good change, I missed being able to use a negative step in a repeat in the old implementation

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +   - Angle start and end positions are always interpreted clockwise from start to end (to avoid ambiguity).
Can I get the to fill in the opposite direction?

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +   - If the formation is around a lead ship that has a facing, then one third of a degree delta is added for every degree that the lead ship turns.
This might be standard ES terminology, so my apologies if this is just for my education, but I was confused be "a lead ship having a facing" meaning "a lead ship whose velocity is different than its heading".

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +   - If the lead ship/object is not moving and not having a facing direction, then the front is in the direction of the system center.
Do some ships not have a facing direction?

2020-06-13 00:45 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +- `ring <nr#>`: Area in the formation where the ship should appear (higher numbers is more outwards on most formations).
I'm confused about these rings vs rings in the old code because the rings in this image have different shapes. In the code a ring is just the next repeat of each line. Are these two different kinds of rings?

2020-06-13 00:50 UTC, thomasballinger commented
One more thing I'm thinking about is "if these lines and arcs don't work for the formation I want to create, can I just use one line per ship to get the behavior I really want. I think the answer is yes.

2020-06-13 08:52 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- (x,y) coordinates are relative to the center of the formation(pattern), with coordinate 0,0 being the center, with positive x being towards the right side of the formation and positive y being towa
Yes, the current examples always have a ship as the center of the formation, but I created this spec (and the example implementation) with the intention of also allowing formations around things like planets and wormholes (with the planet or wormhole being the center of the formation).

2020-06-13 08:54 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `symmetry [x] [y]`: Indicates if a formation should be considered symmetric. Symmetric formations allow for nicer and more desired behaviour on turns.
Keywords `flippable [x] [y]` and `rotatable <angle>` will indeed reflect better what those keywords do. I'll change the spec to use those keywords.

2020-06-13 09:04 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - `rotational <nr#>`: Indicates rotational symmetry (nr is in range 0 to 360). Rotational symetric formations don't need to turn fully to become aligned with the leadship/reference again.
Using a small n like 1 would be fine implementation wise. This would result in a formation that doesn't turn a lot even if the lead ship does changes direction a lot.

I expect angles to be more clear, especially if we remove the keyword symmetry (and just use rotatable here).

2020-06-13 09:47 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `line`: Begins a line.
Yes, that makes a lot of sense and an earlier version of the formations spec (around the time of the initial proposal in https://github.com/endless-sky/endless-sky/issues/4438) actually had a keyword for this.
It also had a keyword for starting from the end, and a keyword to have repeat lines alternatively starting from the start and the end. And a keyword for extending lines so that positions/positionnumbers move along the line when the formations grows.

I removed all those keyword in later versions of the spec, since the spec was already quite complex and I was able to also create centered lines by having 2 opposite lines starting from about the same position.
The alternating start-from-begin and start-from-end were also used in the "delta tailing" formation without those keywords by having 2 different lines repeating interwoven.

Maybe we should add the `center` keyword back, since it will make creating a centered line quite a bit easier. Do you feel we should also add some of those other keywords back?

2020-06-13 09:50 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +      - The default spacing is 2; so twice the radius of the largest ship in the formation.
Yes, that is what it should have said before my last update. But my last update changed all defaults to be in pixels, so then the default spacing would also need to be in pixels. (160 pixels, twice the radius of a Sparrow was working nicely as default in some earlier tests).

I'll update this text.

2020-06-13 10:05 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +         - If a line has an end-coordinate, slots and no spacing, then spacing is automatically calculated (instead of the default being used).
The older versions of the spec didn't support the `end` keyword, because it overlaps with start-angle, slots and spacing. We could also completely remove one of the following combinations and still have the same "expressiveness" without multiple ways to specify the same information:
- the `spacing` and `start angle` keywords
- the `slots` and `start angle` keywords
- the `end` keyword

What would you prefer, remove some of those keywords? (And if so, then which one?) Or have some load-time checks on over-constraining due to overlap in keywords?

2020-06-13 10:15 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - Angle start and end positions are always interpreted clockwise from start to end (to avoid ambiguity).
Good catch. Older versions of the spec allowed this by interpreting angles of 0 to 360 clockwise and angles of 0 to -360 counter-clockwise, but this was lost in the last version of the spec.
I think we should also check here if we want to remove some keywords to remove ambiguity, similar to the above suggestion for lines and we should also check that whatever we choose still supports filling in the opposite direction.

2020-06-13 10:22 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - If the formation is around a lead ship that has a facing, then one third of a degree delta is added for every degree that the lead ship turns.
This text is a bit confusing indeed. I'll add that the front (facing) of the ship is pointing in a different direction that where it is moving to.

2020-06-13 10:23 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - If the lead ship/object is not moving and not having a facing direction, then the front is in the direction of the system center.
This is for formations that are around things like planets and wormholes, where the planet or wormhole is the center of the formation.
I'm not sure if all of those have a facing direction.

2020-06-13 10:31 UTC, petervdmeer commented
> One more thing I'm thinking about is "if these lines and arcs don't work for the formation I want to create, can I just use one line per ship to get the behavior I really want. I think the answer is yes.

Yes, that is correct.
You could also create a formation(pattern) uniquely for each ship (with each formation being 1 line of 1 position), then you would also not have the automatic position replacement.

2020-06-13 13:31 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- (x,y) coordinates are relative to the center of the formation(pattern), with coordinate 0,0 being the center, with positive x being towards the right side of the formation and positive y being towa
Updated the text a bit (I hope it is more clear now).

2020-06-13 13:31 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `symmetry [x] [y]`: Indicates if a formation should be considered symmetric. Symmetric formations allow for nicer and more desired behaviour on turns.
Changed to `flippable` and `rotatable`.

2020-06-13 13:32 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - `rotational <nr#>`: Indicates rotational symmetry (nr is in range 0 to 360). Rotational symetric formations don't need to turn fully to become aligned with the leadship/reference again.
I added some text about using a small n and when it could be desired to do so.

2020-06-13 14:15 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +- `line`: Begins a line.
I agree that it's gotten quite complex. Unlike polar coordinates or the ability to use spacing or start/end to specify number, this is something I wanted when trying to build a formation, so I think we should add this one back. Good point about two lines going out though, if that works maybe not. Won't two lines in opposite directions have one line filled first, then the other? Or has that changed?
![2020-06-13 07 11 43](https://user-images.githubusercontent.com/458879/84570933-33b3ee00-ad45-11ea-9119-abf1ef4128b8.gif)

2020-06-13 14:22 UTC, thomasballinger commented on docs/rfcs/formation_flying.md
> +         - If a line has an end-coordinate, slots and no spacing, then spacing is automatically calculated (instead of the default being used).
I would prefer a check that both aren't used in the same place, but I'd like to keep slots.

I don't love using angle, but I do like specifying how many ships are in a row. I think plugin/content authors will want to describe exactly how a set of e.g. 7 ships in one fleet will fly, which makes start/end pretty finicky since they need to guess numbers that will make the right number of ships fit, and number of ships in a line could change when size of the ships changes.

2020-06-13 15:25 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `line`: Begins a line.
> Won't two lines in opposite directions have one line filled first, then the other? Or has that changed?

You are right. One line would be filled first and then the other. This is a good reason to (re-)add the keyword for centring. I'll add it back to the spec.

2020-06-13 16:09 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +         - If a line has an end-coordinate, slots and no spacing, then spacing is automatically calculated (instead of the default being used).
My proposal was to keep 'start' (coordinate), 'end' (coordinate) and 'slots' and to remove the keywords 'angle' and 'spacing' for lines. That seems to match with the preference you indicate here.
Slots will be the only number that determines how many ships there will be on a line, so that should be quite straight-forward for plugin/content authors.

2020-06-13 17:40 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +      - The default spacing is 2; so twice the radius of the largest ship in the formation.
Text was updated. And then deleted due to removal of this keyword.

2020-06-13 17:42 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +         - If a line has an end-coordinate, slots and no spacing, then spacing is automatically calculated (instead of the default being used).
Maybe a bit fast, but I applied the changes as discussed. Let's see if this makes the specification simpler. (And if not, then let's discuss how to proceed.)

2020-06-13 18:10 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +   - Angle start and end positions are always interpreted clockwise from start to end (to avoid ambiguity).
I fixed this (and the conflicting keywords) by removing the end-coordinate and spacing for arcs and by allowing the angle to range from -360 to 360. Please feel free to re-review the update and check if it is better or not.

2020-06-13 18:38 UTC, petervdmeer commented on docs/rfcs/formation_flying.md
> +- `line`: Begins a line.
I added `centered` back as keyword and I added the keywords `originating` and `extending` to help proper centering over multiple rings.

I also added alternating. The alternating keyword will work nicely for the pattern you posted here if ships move to earlier positions.

2020-06-13 22:33 UTC, thomasballinger approved these changes
Thanks for addressing all this, I think this sounds great.

2021-08-11 14:12 UTC, MCOfficer commented
CI failure is due to an outdated workflow. Either merge master or ignore it, RFCs arent testable anyways.

2022-04-21 18:25 UTC, petervdmeer commented
I just updated the specification to use some less mathematical and more context-aware keywords.

2024-06-17 10:13 UTC, TheGiraffe3 commented
This should be closed because of its in the main game it doesn’t need to be implemented twice here.

2024-06-17 10:24 UTC, closed without merging