Outfit Types
EndlessSkyCommunity/endless-sky pull request #57
Opened 2021-09-14 14:15 UTC by quyykk

## Feature Details

This (small) RFC is for outfit types. Basically an additional node you can add to various outfits to group them together. This then enables content creators to for example remove any outfit from the group.

The main use case for this is to enable species specific hyperdrives.

I'm basically looking for feedback on this particular solution to the problem. Tehhowch mentioned wanting a RFC, so yeah this is it. The only two implementations I could think of (this RFC and outfit variants) are mentioned in it.

## Usage Example

```
outfit Hyperdrive
    type Hyperdrive
outfit "Scram Drive"
    type Hyperdrive

# ... in a mission
on offer
    outfit type Hyperdrive -1 # removes either a Hyperdrive or a Scram Drive
    require type Hyperdrive # require either a Hyperdrive or a Scram Drive
```

2021-09-14 14:48 UTC, MCOfficer requested changes
Also note the inconsistent use of `\`"type"\`` `"type"`

2021-09-14 14:48 UTC, MCOfficer commented on docs/rfcs/text/0000-outfit-types.md
> +Now the outfit `Hyperdrive` belongs to/ the type (or is a) `Hyperdrive`. The type name can be anything, it has no relation at all with the outfit. This type is also not shown in the UI, it's for inte
```suggestion
Now the outfit `Hyperdrive` belongs to the type (or is a) `Hyperdrive`. The type name can be anything, it has no relation at all with the outfit. This type is also not shown in the UI, it's for internal use only.
```

2021-09-14 17:30 UTC, MCOfficer approved these changes

2021-09-14 17:31 UTC, MCOfficer commented
Well that wasnt the button i was looking for. FTR, i dont have an opinion on the PR, just dismissing my previous request for changes.

2023-06-14 23:01 UTC, lumbar527 approved these changes
I want this!

2023-06-15 01:38 UTC, Zitchas commented
This could certainly be useful, yes. I'd like it.

2024-06-17 10:11 UTC, TheGiraffe3 commented
Last updated a year and two days ago… @quyykk are you going to keep working on this?

2024-06-17 10:24 UTC, closed without merging